name: encounter_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  readmore: ^2.2.0
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  dio: ^5.3.3
  fluttertoast: ^8.2.4
  flutter_secure_storage: ^9.0.0
  firebase_performance: ^0.10.0
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: El Messiri
      fonts:
        - asset: assets/fonts/ElMessiriRegular.ttf
          weight: 400
    - family: Manrope
      fonts:
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
    - family: Canela Trial
      fonts:
        - asset: assets/fonts/CanelaTrialRegular.ttf
          weight: 400
        - asset: assets/fonts/CanelaTrialMedium.ttf
          weight: 500
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/SegoeUISemibold.ttf
          weight: 600
